### ISSUE TITLE
Objective cards to have their own URI

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#28]
![screen shot 2015-05-05 at 10 32 40](https://cloud.githubusercontent.com/assets/4499581/7470097/0d443bb4-f312-11e4-97b4-5c6cbc3b9079.jpg)

![screen shot 2015-05-05 at 10 32 25](https://cloud.githubusercontent.com/assets/4499581/7470099/107fcad2-f312-11e4-9375-07f4cddb40e9.jpg)

**Comment by pgreenwo** [comment]
That shows the URI for a POSC Map (Board) with an Objective (card) opened for editing.  There are two reasons why I want Objectives (Cards) to have their own URI:

1) SEO friendly content for public POSC Maps - these should allow spiders to crawl between objectives, maps and the top level domain page.
2) To allow people to forward a reference to an Objective (card), rather than the POSC Map (Board) in general.

Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by pgreenwo** [comment]
Please show me how this has been achieved before closing.

**Comment by alanshaw** [comment]
You should now be able to link directly to objectives like so:
http://posc.meteor.com/map/ReHxwj3dHLKzdDY8C#/edit/wwZXqhwR6NJsqnPvK

The URL changes when you bring up the edit modal. Is that as expected?

**Comment by pgreenwo** [comment]
Perfect. Thanks.
Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>
