### ISSUE TITLE
Scale board text with browser zoom / implement zoom.

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#29]
![screen shot 2015-05-05 at 10 38 39](https://cloud.githubusercontent.com/assets/4499581/7470227/edd27682-f312-11e4-9e6e-9c8d17e9ad3a.jpg)

Just like this is not responsive?

![screen shot 2015-05-05 at 10 38 52](https://cloud.githubusercontent.com/assets/4499581/7470233/fdb493fa-f312-11e4-870a-111077e96879.jpg)

**Comment by pgreenwo** [comment]
Since the POSC Map (what Tableflip has been calling a board) is a map, the kind of shuffling of content you see when a website is responsive is problematic.  You can’t have bits of a map suddenly pushed into other places, or the whole this ceases to make sense.

The text overflow and the scaling need to work together.  Zooming allows you to see the whole map on your screen, but if it makes the text overflow then it looks horrible.
Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by alanshaw** [comment]
I must admit I'm not sure how zooming fits in here, browser zoom increases/decreases the size of all page elements, including text, so zooming in/out isn't going to allow you to see more/less text on an objective.

We've fixed the text overflow issue for objectives so long text will be shortened with ellipsis when longer than the space it needs to occupy. Also the [objective card bubble](https://github.com/tableflip/posc/issues/26) shows the full card info - is there anything more we need to do here?

**Comment by pgreenwo** [comment]
Turning off "Zoom Text only" prevents it from overspilling on different zooms.  That's O.K.

However, I don't see the ellipsis approach described working...

![priority](https://cloud.githubusercontent.com/assets/7540627/7564691/34b3ff80-f7e1-11e4-91dc-3e3c7e5dd411.png)
