### ISSUE TITLE
Editable board title (scope) timeframe and update date.

### ISSUE THREAD

**Issue by bmordan** [tableflip/posc#30]
![screen shot 2015-05-05 at 10 41 18](https://cloud.githubusercontent.com/assets/4499581/7470268/50099326-f313-11e4-9f8e-1a667ce6ac10.jpg)

Like this? for editable update date?

![screen shot 2015-05-05 at 10 42 11](https://cloud.githubusercontent.com/assets/4499581/7470414/c5700c2a-f314-11e4-8313-34158ee94ea8.jpg)

**Comment by pgreenwo** [comment]
You’re showing a card being edited, not the board. A board should have a title and indicate a timeframe.  This current one looks to me as if it is titled “Board Priorities”.  I’d like to be able to edit that… and also add a text field, probably the other end of the same blue bar, to allow users to indicate the timeframe (which is not the same as a date).

Actually, “card" and “board" are Tableflip originated terms and I’d like to move beyond them because they reinforce a paradigm about the tool that is wrong.  I think in terms of a POSC Map, Scope, Timeframe, Priorities, Sequence, Objectives and Outcomes. POSC stands for Prioritised Objective Setting and Communication.  A POSC Map has a Scope and a Timeframe. A row on the POSC Map is a sequence of objective that have to be achieved, with has a priority level.  The right hand objective typically describes a desired outcome, the left hand objective is the first in a sequence of objectives to achieve the right-hand - outcome - objective.  Why have I chosen these terms?  Because they seem to have about the right level of imprecision (or fuzziness, if you like).

There is a problem that Tableflip has baked the board/card concept into the code...

I presume that the last edited field is to do with showing recent changes - I I don’t think it needs to be a text field editable by the user.

I’m back ashore now; please Skype me if you wish to discuss these things.

Warm regards,

Philip Greenwood

Landline: +44 20 7193 8021 | Cell: +44 7973 615 045 | Skype: philngreenwood | Connect: LinkedIn <http://www.linkedin.com/in/philipgreenwood>

**Comment by pgreenwo** [comment]
Please change the default text for these two fields:

On the left: "Click to Enter Scope"
On the right: "Click to Enter Timeframe"
